name: catbreeds
description: A new Flutter project.

publish_to: 'none'

version: 0.3.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  auto_size_text: 3.0.0
  cached_network_image: 3.3.1
  cupertino_icons: 1.0.6
  flutter_dotenv: 5.1.0
  http: 1.1.0
  provider: 6.1.1
  url_launcher: 6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
